[tool.poetry]
name = "ai-ethics"
version = "0.1.0"
description = ""
authors = ["reidefe <reidefe@gmail.com>"]
readme = "README.md"
packages = [{include = "ai_ethics"}]

[tool.poetry.dependencies]
python = "3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
